### ISSUE TITLE
Give error when rdf cut and potential cut do not match

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/msibi#18]
On my latest runs I changed my rdf cutoff but forgot to also update the potential cutoff and it was causing an error at the potential update step.  We should probably check and throw an error if they don't match.  Or, maybe we juts set a single cutoff parameter that is used for both?  If there is some reason why you want different cutoff distances, then we should handle truncating when necessary to deal with different sized data sets.

I personally think we should either throw an error if they don't match, or set a single cutoff parameter in the `MSIBI` class that gets used for both.

**Comment by chrisjonesBSU** [comment]
@jennyfothergill I'm interested in what you think is the best way to handle this? Enforce that they match, or do we just use one `cutoff` parameter?

**Comment by jennyfothergill** [comment]
I like the idea of a single cutoff. Especially if we're only going to throw an error if they're different.

**Comment by chrisjonesBSU** [comment]
This is no longer an issue with the latest PR.
