### ISSUE TITLE
Clean up environment files

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/msibi#19]
It looks like the `.yml` files have a few packages that aren't used anymore. Maybe some of them are due to the tutorial notebooks. I wonder if a better idea might be to create a separate coarse-graining tutorial repo that show show to use both GRiTS and MSIBI together? 

- mdtraj
- foyer
- antefoyer
- p3Dmol
- jupyter

Possibly some others.

**Comment by jennyfothergill** [comment]
I think that's a great idea. Or if we don't want to make a separate repo, simply a separate environment file in the examples directory could be good.

**Comment by chrisjonesBSU** [comment]
That's not a bad idea too. I think a tutorial and some examples that go through the CG process from initializing AA systems, running a quick sim, CGing them with GRiTS and then running MSIBI would have enough content for a stand-alone repository. Especially if we can add more and more examples of different systems.
